"""Generate glossary and first-use evidence from explicit chapter definitions."""
from pathlib import Path
import argparse
import json
import re
ROOT=Path(__file__).resolve().parents[1]
NAMES={"dna":"DNA","rna":"RNA","physical-medium":"physical medium","dna-computing":"DNA computing",
       "computational-gene":"computational gene","research-program":"research program",
       "expression":"gene expression","regulation":"gene regulation"}

def group(source,start):
    assert source[start]=="{"
    depth=1
    end=start+1
    while depth:
        if source[end]=="{":depth+=1
        elif source[end]=="}":depth-=1
        end+=1
    return source[start+1:end-1],end

def plain(s):
    s=re.sub(r"~?\\cite\{[^}]+\}","",s)
    s=re.sub(r"\\(?:label|index)\{[^}]+\}","",s)
    s=re.sub(r"\\(?:gls|Gls)\{([^}]+)\}",lambda m:NAMES.get(m[1],m[1]),s)
    s=re.sub(r"\\Teach\{([^}]+)\}",lambda m:NAMES.get(m[1],m[1]),s)
    s=re.sub(r"\\[A-Za-z]+\*?(?:\[[^]]*\])?","",s)
    return re.sub(r"\s+"," ",s.replace("{"," ").replace("}"," ").replace("~"," ")).strip()

def outputs():
    source=(ROOT/"tex/undergraduate/ch01.tex").read_text()
    prefix="DNAU-01" if ROOT.name=="dna-computing-book" else "EVOU-01"
    definitions=[]
    related={"input":"output","output":"input","rule":"computation","computation":"rule","step":"rule",
             "dna":"molecule","molecule":"dna","strand":"sequence","sequence":"strand",
             "representation":"information","information":"representation",
             "function":"program","program":"function","Python":"program",
             "atom":"bond","bond":"atom","physical-medium":"representation","dna-computing":"dna",
             "gene":"expression","expression":"regulation","regulation":"expression","genome":"gene",
             "rna":"protein","protein":"rna","cell":"genome","context":"condition",
             "threshold":"condition","condition":"threshold","trace":"execution","execution":"trace",
             "computational-gene":"analogy","analogy":"computational-gene",
             "research-program":"hypothesis","hypothesis":"evidence","baseline":"hypothesis","evidence":"hypothesis"}
    section_fig={"count":"F1","rule":"F2","code":"code listing and generated trace",
                 "representation":"F3","dna":"F4","bridge":"F5","roadmap":"F6",
                 "program":"F1","boundary":"F2","biology":"F3","analogy":"F4","research":"F5"}
    gl=["% Generated by scripts/audit_undergraduate.py from Teach definitions.\n"]
    for m in re.finditer(r"\\Teach\{([^}]+)\}",source):
        key=m[1]
        definition,end=group(source,m.end())
        sec=re.findall(r"\\label\{(sec:[^}]+)\}",source[:m.start()])[-1]
        name=NAMES.get(key,key)
        description=plain(definition).rstrip(".")
        fig=section_fig[sec.split(":")[1]]
        figure=prefix+"-"+fig if fig.startswith("F") else fig
        sentence=name+" "+plain(definition)
        # Earliest exact displayed-name occurrence in the chapter, including title/objective previews.
        readable=plain(source[:m.start()])+sentence
        match=re.search(r"(?i)(?<![\w-])"+re.escape(name)+r"(?![\w-])",readable)
        first=sentence
        if match:
            left=max(readable.rfind(". ",0,match.start()),readable.rfind("? ",0,match.start()))
            right=re.search(r"[.!?](?:\s|$)",readable[match.end():])
            first=readable[left+2:match.end()+(right.end() if right else len(readable))].strip()
        definitions.append({"key":key,"name":name,"firstSentenceOrHeadingPreview":first,
                            "definitionSentence":sentence,"section":sec,"figure":figure,
                            "glossaryKey":key,"related":related[key]})
        gl.append("\\newglossaryentry{"+key+"}{name={"+name+"},description={"+
                  description+". First taught in Section~\\ref{"+sec+"}; see also \\glslink{"+
                  related[key]+"}{\\glsentryname{"+related[key]+"}}.}}\n")
    lines=["# Chapter 1 terminology audit\n\n",
           "Generated from the canonical manuscript; definitions are not maintained in a second prose copy. "
           "Headings, the opening question and learning-objective previews may name a destination before its definition. "
           "These previews do not require the reader to use that concept. Ordinary words such as rule and information "
           "are refined before their technical use. The first-encounter column includes these early previews rather than hiding them.\n\n",
           "| Term | First sentence or heading preview | Precise definition sentence | Location | Figure / worked illustration | Glossary key |\n",
           "|---|---|---|---|---|---|\n"]
    for d in definitions:
        lines.append("| "+" | ".join(str(d[k]).replace("|","/") for k in
                     ("name","firstSentenceOrHeadingPreview","definitionSentence","section","figure","glossaryKey"))+" |\n")
    lines.append("\n## Additional syntax and supporting words\n\n"
                 "Optional code defines def, return, input-name substitution, parentheses, colon and indentation in Section 1.3; "
                 "Evolutor also explains if, quoted words and early return. No library, tensor or training syntax is required. "
                 "The DNA chapter defines decimal in Figure 1.3's caption and symbol in Section 1.7. "
                 "Its atom and bond descriptions are preliminary, not chemical structure claims. "
                 "Evolutor defines amino acids as protein building units, sequence as written order, "
                 "and stored state as information retained between steps; each receives deeper treatment later. "
                 "Roadmap stage names are destinations, not hidden prerequisites.\n\n"
                 "Internal review: unknown-word candidates in captions, exercises and answers were read separately. "
                 "This explicit inventory cannot certify that an actual novice knows every ordinary word; learner testing remains open.\n")
    return {"tex/undergraduate/glossary.tex":"".join(gl),
            "research/undergraduate-ch01-terminology.md":"".join(lines),
            "pedagogy/ch01-terms.json":json.dumps(definitions,indent=2,ensure_ascii=False)+"\n"}

def main():
    p=argparse.ArgumentParser()
    p.add_argument("--check",action="store_true")
    args=p.parse_args()
    for name,content in outputs().items():
        dest=ROOT/name
        if args.check:
            if not dest.exists() or dest.read_text()!=content:raise SystemExit("Stale terminology: "+name)
        else:
            dest.parent.mkdir(parents=True,exist_ok=True)
            dest.write_text(content)
    print("Chapter 1 glossary and terminology audit "+("fresh" if args.check else "written"))
if __name__=="__main__":main()
