"""Regenerate Chapter 1 records and LaTeX table from the executable example."""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "code/minievolutor"))
from minievolutor.dispatch_reference import chapter_example


def artifacts():
    from dataclasses import asdict
    records = [{"size": size, "method": method, **asdict(result)}
               for size, method, result in chapter_example()]
    record = {"model": "logical event counts; not timing", "runs": records}
    rows = [f"{r['size']} & {r['method'].replace('_', ' ')} & {r['gate_tests']} & "
            f"{r['lookups']} & {r['firings']} & {r['value']}" + r" \\"
            for r in records]
    table = (r"\begin{tabular}{rlrrrr}" + "\n" +
             r"\toprule $K$ & Strategy & Gates & Lookups & Firings & Output \\" +
             "\n" + r"\midrule" + "\n" + "\n".join(rows) + "\n" +
             r"\bottomrule\end{tabular}" + "\n")
    return {"ch01.json": json.dumps(record, indent=2) + "\n",
            "ch01-table.tex": "% Generated by scripts/chapter01_artifacts.py; do not edit.\n" + table}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "book/results"
    for name, content in artifacts().items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated artifact: {path}")
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(path.relative_to(ROOT))
