"""Generate Chapter 2 records and the printed table from exact reference code."""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "code/minievolutor"))
from minievolutor.leaky_state import chapter_example


def artifacts():
    steps = chapter_example()
    record = {"model": "exact discrete state recurrence; not measured biology",
              "parameters": {"production": "2", "loss": "1/2", "initial": "0"},
              "units": "arbitrary state units; loss is a fraction per update",
              "steps": [{"time": s.time, "signal": s.signal, "before": str(s.before),
                         "after": str(s.after), "instantaneous": str(s.instantaneous)}
                        for s in steps]}
    def fraction(value):
        text = str(value)
        return "$" + text + "$"
    rows = [f"{s.time} & {s.signal} & {fraction(s.before)} & {fraction(s.after)} & "
            + fraction(s.instantaneous) + r" \\" for s in steps]
    table = (r"\begin{tabular}{rrrrr}" + "\n" +
             r"\toprule $t$ & $u_t$ & $x_t$ & $x_{t+1}$ & $y_t$ \\" +
             "\n" + r"\midrule" + "\n" + "\n".join(rows) + "\n" +
             r"\bottomrule\end{tabular}" + "\n")
    return {"ch02.json": json.dumps(record, indent=2) + "\n",
            "ch02-table.tex": "% Generated by scripts/chapter02_artifacts.py; do not edit.\n" + table}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "book/results"
    for name, content in artifacts().items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated artifact: {path}")
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(path.relative_to(ROOT))
